### ISSUE TITLE
catch E344 and silently fail

### ISSUE THREAD

**Issue by sharethewisdom** [dylanaraps/root.vim#4]
In order to allow editing a new file in memory which has a new path, I create directories on FileWritePre. When entering such a buffer, I would like root#FindRoot() to silently fail when it throws `E344: Can't find directory ...`.

Would you like to add a `g:root#error = 0`?

**Comment by dylanaraps** [comment]
I just silenced the first `lcd`, there's already some error handling after it that exits the plugin. You can also use `g:root#echo` to turn plugin messages on/off.

**Comment by sharethewisdom** [comment]
thanks for your response.

The assumption here is that only trailing segments in a new file's path could be missing in the filesystem. (e.g. `/home/user/gitdir/this-is-a-dir/not-a-dir/also-not-a-dir/new.file`) So, do you think it is better to instead `catch /^Vim\%((\a\+)\)\=:E344/` and loop up the tree until an existing directory is found? The main pattern loop would remain as-is, and root.vim would jump over the troubling segments.
